CODE_SUCCESSED = 200
CODE_NOTFIND = 203
CODE_NETERROR = 401
CODE_FAILURE = 402

MESSAGE_SUCCESSED = "成功"
MESSAGE_FAILURE = "失败"
MESSAGE_NETERROR = "网络异常"

MESSAGE_UPDATE_SUCCESSED = "更新成功"
MESSAGE_UPDATE_FAILURE = "更新失败"

MESSAGE_APPEND_SUCCESSED = "添加成功"
MESSAGE_APPEND_FAILURE = "添加失败"

MESSAGE_LOGIN_SUCCESSED = "登录成功"
MESSAGE_LOGIN_FAILURE = "用户名或密码错误"

MESSAGE_DELETE_SUCCESSED = "删除成功"
MESSAGE_DELETE_FAILURE= "删除失败"
MESSAGE_DEPARTMENT_DELETE_FAILURE = "删除失败:此部门包含员工"
MESSAGE_JOB_DELETE_FAILURE = "删除失败:此职业包含员工"

MESSAGE_FLUSH_SUCCESSED = "刷新成功"

DATABASE_LOCATION = "localhost"
DATABASE_PORT = 3306
DATABASE_LOCATION_AND_PORT = "http://47.108.143.150:23451"